### ISSUE TITLE
invalid character 'c' looking for beginning of value 

### ISSUE THREAD

**Issue by maurosc3ner** [degauss-org/pm#11]
Hi, 

I am getting the following error when using degauss pm. I have tried two versions:
1. The latest 0.2.0 crashes 

`docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/pm:0.2.0 covid_0_degauss.pm.before.csv`
![image](https://user-images.githubusercontent.com/4038971/204679560-ac718dbe-caf6-4978-a08e-441ce8fdcc0a.png)

2. The 0.1.3 that was used to build the original dataset seems going a little bit further:

`docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/pm:0.1.3 covid_0_degauss.pm.before.csv `
![image](https://user-images.githubusercontent.com/4038971/204679674-42048cc9-996e-4aae-aa13-d3b8ab5cadfe.png)

My platform:
MacBook Pro (M1 Max)
macOS Monterey 12.4

Any help is welcome,

Esteban

**Comment by maurosc3ner** [comment]
Hi, 

Just a brief update about. I re run same exactly same files + command using pm:0.1.3 + windows 10 machine x64 without any issues:
![image](https://user-images.githubusercontent.com/4038971/204829668-3d45f4bc-e96a-4e24-b0a8-c08c710ce872.png)

It was not possible to match docker engine, but they are using the latest on each platform.

Thanks,
Esteban

**Comment by cole-brokamp** [comment]
That's good that you got it to work somehow.  Did the other failures happen repeatedly at the same point?  The different versions of the container are still attempting to download the same files from S3, so I would assume that it could be intermittent connection problems.  Since it saves the downloaded files in between runs, it will eventually succeed if ran enough times.

**Comment by cole-brokamp** [comment]
Closing this for now.  Please reopen if you have any more problems, thanks!
